# Generated by Django 5.1.6 on 2025-03-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('ready', 'Lista'), ('delivered', 'Entregada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KitchenOrder',
        ),
    ]
