# Generated by Django 5.1.6 on 2025-03-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_style_dish_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='style',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
