# Generated by Django 5.1.6 on 2025-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_dish_ingredients_remove_style_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='ingredients_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
